#!/usr/bin/env bash
# scripts/check-guide-snippets.sh
# Type-checks every ```rust block in docs/using-gmcrypto-core.md.
#
# Why: check-doc-sync.sh only proves the EN and zh-CN guides carry byte-identical
# code blocks. It cannot tell whether those blocks compile, which is how three
# non-compiling snippets shipped (§0 `from_point`, PR #22; §7 destructuring an
# `Option`; §12 moving a non-`Clone` `Certificate` twice, PR #25). This script
# closes that class.
#
# How: the guide's blocks are deliberately fragments — they name `key`, `nonce`,
# `plaintext`, … without defining them. Each block is therefore wrapped in its
# own `fn` behind a fixture prelude (the demo's public `DEMO_*` constants and
# helpers, plus a section-appropriate `key`), the whole thing is written to a
# scratch crate under target/guide-snippets/ that reuses this repo's exact
# `[dependencies]` / `[features]` tables and Cargo.lock, and `cargo check
# --all-features` runs over it. Only the EN guide is read: check-doc-sync.sh
# already guarantees the zh-CN blocks are identical.
#
# Fence tags: a block opened with ```rust,ignore is skipped; every other ```rust
# block must type-check. Errors point at the generated file; the comment on the
# line above each `fn snippet_<line>` names the guide line the block starts on.
set -euo pipefail

if [ "$#" -ne 0 ]; then
    echo "usage: $0   (no arguments; run from the repo root)" >&2
    exit 2
fi
for f in Cargo.toml Cargo.lock docs/using-gmcrypto-core.md src/lib.rs; do
    if [ ! -f "$f" ]; then
        echo "ERROR: file not found: $f (run from the repo root)" >&2
        exit 2
    fi
done
command -v python3 >/dev/null || { echo "ERROR: python3 is required" >&2; exit 2; }

ROOT="$(pwd)"
OUT="$ROOT/target/guide-snippets"
mkdir -p "$OUT/src"

# --- Cargo.toml: this repo's dependency pin and feature table, verbatim, plus a
# path dependency on the demo crate itself for the fixture helpers. ---------
{
    cat <<EOF
# Generated by scripts/check-guide-snippets.sh — do not edit.
[package]
name = "guide-snippets"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

EOF
    # Copy [dependencies] and [features] exactly as the demo declares them.
    awk '
        /^\[dependencies\]/ { p = 1 }
        /^\[features\]/     { p = 1 }
        /^\[\[example\]\]/  { p = 0 }
        p { print }
    ' "$ROOT/Cargo.toml"
    cat <<EOF

[dependencies.gm-crypto-rs-demo]
path = "$ROOT"
EOF
} > "$OUT/Cargo.toml"
cp "$ROOT/Cargo.lock" "$OUT/Cargo.lock"

# --- src/main.rs: one fn per snippet. -------------------------------------
GUIDE="docs/using-gmcrypto-core.md" ROOT="$ROOT" OUT="$OUT" python3 - <<'PY'
import os, re, sys

guide = os.environ["GUIDE"]
root = os.environ["ROOT"]
out = os.path.join(os.environ["OUT"], "src", "main.rs")
lines = open(guide, encoding="utf-8").read().split("\n")

# Section-specific `key` binding: the guide reuses the name `key` for an HMAC
# key (§2), an SM2 private key (§3–§5) and an SM4 key (§6–§8).
KEY_BY_SECTION = {
    2: "let key: &[u8] = &DEMO_HMAC_KEY;",
    3: "let key: Sm2PrivateKey = sample_private_key();",
    4: "let key: Sm2PrivateKey = sample_private_key();",
    5: "let key: Sm2PrivateKey = sample_private_key();",
    6: "let key: [u8; 16] = DEMO_SM4_KEY;",
    7: "let key: [u8; 16] = DEMO_SM4_KEY;",
    8: "let key: [u8; 16] = DEMO_SM4_KEY;",
}

def data(name):
    return f'include_bytes!("{root}/examples/data/{name}")'

PRELUDE = f"""
    let mut rng = os_rng();
    let msg: &[u8] = DEMO_HMAC_MSG;
    let password: &[u8] = DEMO_PBKDF2_PASSWORD;
    let salt: &[u8] = DEMO_PBKDF2_SALT;
    let iv: [u8; 16] = DEMO_SM4_IV;
    let counter: [u8; 16] = DEMO_SM4_IV;
    let nonce: [u8; 12] = [0u8; 12];
    let aad: &[u8] = b"associated data";
    let plaintext: &[u8] = b"plaintext";
    let pt: &[u8] = plaintext;
    let plaintext_block: [u8; 16] = [0u8; 16];
    let key32: [u8; 32] = core::array::from_fn(|i| i as u8);
    let tweak: [u8; 16] = [0u8; 16];
    let sector: &[u8] = &[0u8; 512];
    let tag: [u8; 32] = [0u8; 32];
    let public: Sm2PublicKey = sample_public_key();
    let d_a: Sm2PrivateKey = sample_private_key();
    let d_b: Sm2PrivateKey = sample_private_key();
    let p_a: Sm2PublicKey = d_a.public_key();
    let p_b: Sm2PublicKey = d_b.public_key();
    let id_a: &[u8] = b"alice";
    let id_b: &[u8] = b"bob";
    // §11 no-confirmation block continues the confirmed block's bindings.
    let init = Sm2KxInitiator::new(&d_a, &p_b, id_a, id_b, 16).expect("kx");
    let (r_a, init_waiting) = init.produce_ephemeral(&mut rng).expect("R_A");
    let resp = Sm2KxResponder::new(&d_b, &p_a, id_a, id_b, 16).expect("kx");
    // §12 TLCP fixtures.
    let pre_master: [u8; 48] = [0u8; 48];
    let client_random: [u8; 32] = [0u8; 32];
    let server_random: [u8; 32] = [0u8; 32];
    let transcript_hash: [u8; 32] = [0u8; 32];
    let cbc_key_block: [u8; CBC_KEY_BLOCK_LEN] = [0u8; CBC_KEY_BLOCK_LEN];
    let client_keys: RecordKeysCbc = RecordKeysCbc::from_key_block(TlcpRole::Client, &cbc_key_block);
    let seq: u64 = 0;
    let content_type: u8 = 0x17;
    // §10 / §12 certificate fixtures (the same public DERs the examples use).
    let ca_der: &[u8] = {data("x509_ca.der")};
    let leaf_der: &[u8] = {data("x509_leaf.der")};
    let root_der: &[u8] = {data("x509_chain_root.der")};
    let int_der: &[u8] = {data("x509_chain_int.der")};
    let sign_der: &[u8] = {data("x509_chain_sign.der")};
    let enc_der: &[u8] = {data("x509_chain_enc.der")};
"""

HEADER = """// Generated by scripts/check-guide-snippets.sh from docs/using-gmcrypto-core.md.
// Each guide ```rust block is the body of one fn below; the comment above it
// names the guide line the block opens on. Compile-only: nothing here runs.
#![allow(
    unused_imports,
    unused_variables,
    unused_mut,
    unused_assignments,
    dead_code,
    unreachable_code,
    unused_must_use,
    clippy::all
)]

use gm_crypto_rs_demo::*;
// §2's constant-time `verify` block continues the block before it without re-importing.
use gmcrypto_core::hmac::HmacSm3;
use gmcrypto_core::sm2::key_exchange::{Sm2KxInitiator, Sm2KxResponder};
use gmcrypto_core::sm2::{Sm2PrivateKey, Sm2PublicKey};
use gmcrypto_core::tlcp::key_schedule::TlcpRole;
use gmcrypto_core::tlcp::record::{RecordKeysCbc, CBC_KEY_BLOCK_LEN};

/// Lets a snippet use `?` on any error type without caring which.
struct SnippetError;
impl<E: core::fmt::Debug> From<E> for SnippetError {
    fn from(_: E) -> Self {
        SnippetError
    }
}

fn main() {}
"""

fence_re = re.compile(r"^(`{3,})(.*)$")
section = None
i = 0
n_checked = n_skipped = 0
parts = [HEADER]
while i < len(lines):
    line = lines[i]
    m = re.match(r"^## (\d+)\.", line)
    if m:
        section = int(m.group(1))
    m = fence_re.match(line)
    if not m:
        i += 1
        continue
    fence, info = m.group(1), m.group(2).strip()
    tags = [t for t in re.split(r"[,\s]+", info) if t]
    start = i + 1  # 1-based line of the opening fence
    body = []
    i += 1
    while i < len(lines) and lines[i] != fence:
        body.append(lines[i])
        i += 1
    if i >= len(lines):
        sys.exit(f"ERROR: unterminated fence opened at {guide}:{start}")
    i += 1
    if not tags or tags[0] != "rust":
        continue
    if "ignore" in tags[1:]:
        n_skipped += 1
        continue
    n_checked += 1
    key = KEY_BY_SECTION.get(section, "")
    indented = "\n".join("        " + l if l else "" for l in body)
    parts.append(f"""
// {guide}:{start} (section {section})
fn snippet_{start}() -> Result<(), SnippetError> {{{PRELUDE}    {key}
    {{
{indented}
    }}
    Ok(())
}}
""")

open(out, "w", encoding="utf-8").write("".join(parts))
print(f"extracted {n_checked} rust blocks from {guide} ({n_skipped} skipped via ```rust,ignore)")
if n_checked == 0:
    sys.exit("ERROR: no ```rust blocks found — wrong file, or the extractor is broken")
PY

# --- Type-check. Shares this repo's target dir so the dependency build is reused.
CARGO_TARGET_DIR="$ROOT/target" cargo check --quiet --all-features \
    --manifest-path "$OUT/Cargo.toml"
echo "OK: every \`\`\`rust block in docs/using-gmcrypto-core.md type-checks under --all-features"
